Develop issue#26
tekuppi1/texserver pull request #29
Opened 2016-12-08 19:33 UTC by hatimitusiropp

2016-12-08 19:34 UTC, hatimitusiropp commented
ReviewerにAssignしておきました！

2016-12-08 22:24 UTC, TakenokoPro commented
@hatimitusiropp 
プルリクあざっす。ベースブランチは変えときますね。

2016-12-08 22:40 UTC, TakenokoTech requested changes
一旦、コメントつけました。

2016-12-08 22:40 UTC, TakenokoPro commented on src/Template/Books/index.ctp
> +<?php
本取得のロジックは最終的には、BookControllerに持っていきます。
↑
動くの確認をできるまでは今のままで良いです。

2016-12-08 22:40 UTC, TakenokoPro commented on src/Template/Books/index.ctp
> +// ※は自分で設定してください
関数として、
```
/**
  * 情報取得のURLを生成
  * serchWord:検索ワード
  * option:その他必要なパラメータ
  */
function generateUrl(serchWord, option); 

/** 
  * APIで通信
  * url: API接続したいurlパス
  */
function callApi(url);

/**
 * DOMにマッピング
 * responce:callApiで取得したjsonデータ？ 
 */
function mapToDom(responce);
```
こんな流れのコントローラを作りたいです。

2016-12-13 03:18 UTC, TakenokoPro commented
6d86ae6
このコミットは別ブランチにしよう。

2016-12-13 03:20 UTC, TakenokoPro commented on src/Template/Books/index.ctp
> +<?php
src/Template/Books/index.ctp
このファイルの追加分は消してちょ

2016-12-29 17:44 UTC, TakenokoPro commented
一旦、#35 で改修させてください。

2016-12-29 17:44 UTC, closed without merging